spring:
  application:
    name: caffbrowser
  datasource:
    url: jdbc:mysql://localhost:3306/caffBrowserDB
    username: root
    password: password
  liquibase:
    change-log: classpath:db/changelog-app.xml
    labels: sample
  mvc:
    static-path-pattern: /public/images/**
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"

server:
  port: 8080
  https: false
  http-port: 8080

security:
  cors:
    enabled: true
  csrf:
    disabled: true
  token-secret: caffbrowsersecret
  access-token-expiration: 6000000 # 100 perc
  refresh-token-expiration: 18000000 # 300 perc

springdoc:
  api-docs:
    path: /api/public/api-docs
  swagger-ui:
    path: /api/public/swagger.html
