spring:
    config:
        activate:
            on-profile: localdb
    datasource:
        url: jdbc:mysql://localhost:3306/caffbrowser
        username: root
        password: Password1

---

spring:
    config:
        activate:
            on-profile: https

server:
    port: 8443
    https: true
    http-port: 8080
    ssl:
        enabled: true
        key-store: classpath:https/caffbrowser.p12
        key-store-password: eldiab
        key-store-type: PKCS12
        key-alias: springboot
