spring:
  application:
    name: caffbrowser
  datasource:
    url: jdbc:mysql://localhost:3306/caffBrowserDB
    username: root
    password: password
  liquibase:
    change-log: classpath:db/changelog-app.xml
    labels: sample
  mvc:
    static-path-pattern: /public/images/**
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 8080
  https: false
  http-port: 8080

security:
  cors:
    enabled: true
  token-secret: caffbrowsersecret
  access-token-expiration:  10800000 # 3 óra
  refresh-token-expiration: 108000000 # 30 óra

springdoc:
  api-docs:
    path: /api/public/api-docs
